name: flutter_web
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/images/
    - assets/portfolios/

flutter_gen:
  output: lib/src/constants
  assets:
    outputs:
      class_name: AppAssets
