name: flutter_web
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.1
  universal_html: ^2.2.4
  url_launcher: ^6.2.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/images/
    - assets/portfolios/

flutter_gen:
  output: lib/src/constants
  assets:
    outputs:
      class_name: AppAssets
